spring:
  application:
    name: yupao-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yupao_backend?useUnicode=true&characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 123456
  # session 失效时间
  session:
    timeout: 86400
    store-type: redis
  redis:
    port: 6379
    database: 0
    host: 127.0.0.1
    timeout: 60000
server:
  port: 8080
  servlet:
    context-path: /api
mybatis-plus:
  global-config:
    db-config:
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
logging:
  level:
    ###打印mybatis日志
    com.yupaoBackend.mapper: debug

